[book]
authors = ["Evan Pratten"]
language = "en"
multilingual = false
src = "docs"
title = "Ludum Dare 50"

[output.html]
mathjax-support = true
theme = "light"
default-theme = "light"
git-repository-url = "https://github.com/Ewpratten/ludum-dare-50"
site-url = "/docs"

[output.html.search]
enable = true

[output.html.print]
enable = true

[rust]
edition = "2021"

[build]
build-dir = "target/book"